apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: users
spec:
  replicas: 1
  selector:
    matchLabels:
      name: users
  template:
    metadata:
      name: users
      labels:
        name: users
        app: backend
    spec:
      containers:
        - name: users
          image: raihany4hy4/users:master
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: rabbit-env-secret
            - secretRef:
                name: users-mongo-env-secret
          ports:
            - containerPort: 3000
          env: 
            - name: PORT
              value: "3000"

---

apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  selector:
    name: users
  ports:
    - port: 3000
      targetPort: 3000
